// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0UVyoKI8ewRXzeJC_U3E1niIttr2CuY',
    appId: '1:306310118708:web:a6be7b54650d867d287961',
    messagingSenderId: '306310118708',
    projectId: 'chatting-app-96adf',
    authDomain: 'chatting-app-96adf.firebaseapp.com',
    storageBucket: 'chatting-app-96adf.appspot.com',
    measurementId: 'G-FDKXRXWBC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77H2lR8FdvGVOMR0ssVnBlr30FtYA-4k',
    appId: '1:306310118708:android:261ac2a8f63c0a9d287961',
    messagingSenderId: '306310118708',
    projectId: 'chatting-app-96adf',
    storageBucket: 'chatting-app-96adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDwqdHL0gruBtyla5mGZfP1WJ2LC8fHE',
    appId: '1:306310118708:ios:0666c085dc2513ac287961',
    messagingSenderId: '306310118708',
    projectId: 'chatting-app-96adf',
    storageBucket: 'chatting-app-96adf.appspot.com',
    androidClientId: '306310118708-tuulul8hb497a7v4vbi4ddsq0anvp121.apps.googleusercontent.com',
    iosClientId: '306310118708-6s68ognbfps9921ev1nabdl81habmr9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDwqdHL0gruBtyla5mGZfP1WJ2LC8fHE',
    appId: '1:306310118708:ios:b0fe86819bcca9c2287961',
    messagingSenderId: '306310118708',
    projectId: 'chatting-app-96adf',
    storageBucket: 'chatting-app-96adf.appspot.com',
    androidClientId: '306310118708-tuulul8hb497a7v4vbi4ddsq0anvp121.apps.googleusercontent.com',
    iosClientId: '306310118708-9mpnq9s1m35f0mi5tu3q6lrcp8jpd4nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
